project:
  type: website
  output-dir: _site\The-Hogan-Lab

website:
  title: "Hogan Lab"
  navbar:
    logo: images/logo.png
    left:
      - href: index.qmd
        text: Home
      - href: mission.qmd
        text: Mission & Values
      - href: team.qmd
        text: Team
      - href: research.qmd
        text: Research
      - href: publications.qmd
        text: Publications
      - href: contact.qmd
        text: Contact

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    page-layout: full